"""Initial schema: sessions and their child tables.

Revision ID: 116acbf70d3b
Revises:
Create Date: 2026-10-01 18:26:01.827932+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "116acbf70d3b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("src_ip", postgresql.INET(), nullable=False),
        sa.Column("src_port", sa.Integer(), nullable=True),
        sa.Column("protocol", sa.String(length=16), nullable=True),
        sa.Column("sensor", sa.String(length=64), nullable=False),
        sa.Column("client_version", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("authenticated", sa.Boolean(), nullable=False),
        sa.Column("command_count", sa.Integer(), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "protocol IS NULL OR protocol IN ('ssh', 'telnet')", name="ck_sessions_protocol"
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(
        "ix_sessions_interactive",
        "sessions",
        ["started_at"],
        unique=False,
        postgresql_where=sa.text("command_count > 0"),
    )
    op.create_index("ix_sessions_src_ip", "sessions", ["src_ip"], unique=False)
    op.create_index("ix_sessions_started_at", "sessions", ["started_at"], unique=False)
    op.create_table(
        "commands",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("input", sa.Text(), nullable=False),
        sa.Column("failed", sa.Boolean(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "seq", name="uq_commands_session_seq"),
    )
    op.create_index("ix_commands_occurred_at", "commands", ["occurred_at"], unique=False)
    op.create_table(
        "file_transfers",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("shasum", sa.String(length=64), nullable=True),
        sa.Column("uploaded", sa.Boolean(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "seq", name="uq_file_transfers_session_seq"),
    )
    op.create_index("ix_file_transfers_shasum", "file_transfers", ["shasum"], unique=False)
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "seq", name="uq_login_attempts_session_seq"),
    )
    op.create_index("ix_login_attempts_password", "login_attempts", ["password"], unique=False)
    op.create_index("ix_login_attempts_username", "login_attempts", ["username"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_login_attempts_username", table_name="login_attempts")
    op.drop_index("ix_login_attempts_password", table_name="login_attempts")
    op.drop_table("login_attempts")
    op.drop_index("ix_file_transfers_shasum", table_name="file_transfers")
    op.drop_table("file_transfers")
    op.drop_index("ix_commands_occurred_at", table_name="commands")
    op.drop_table("commands")
    op.drop_index("ix_sessions_started_at", table_name="sessions")
    op.drop_index("ix_sessions_src_ip", table_name="sessions")
    op.drop_index(
        "ix_sessions_interactive",
        table_name="sessions",
        postgresql_where=sa.text("command_count > 0"),
    )
    op.drop_table("sessions")
    # ### end Alembic commands ###
