"""Per-address intelligence: geolocation and network.

Revision ID: b176a98eaeba
Revises: 116acbf70d3b
Create Date: 2026-10-01 20:19:08.730926+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b176a98eaeba"
down_revision: str | None = "116acbf70d3b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ip_intel",
        sa.Column("ip", postgresql.INET(), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("country_name", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("asn", sa.Integer(), nullable=True),
        sa.Column("as_org", sa.Text(), nullable=True),
        sa.Column("geo_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("ip"),
    )
    op.create_index("ix_ip_intel_asn", "ip_intel", ["asn"], unique=False)
    op.create_index("ix_ip_intel_country_code", "ip_intel", ["country_code"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ip_intel_country_code", table_name="ip_intel")
    op.drop_index("ix_ip_intel_asn", table_name="ip_intel")
    op.drop_table("ip_intel")
    # ### end Alembic commands ###
